"""
emailer.py  –  Sends matched jobs as a formatted HTML email via Gmail SMTP.
"""

import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText
from datetime             import datetime
from config               import GMAIL_SENDER, GMAIL_PASSWORD, NOTIFY_EMAIL, MIN_MATCH_PCT

log = logging.getLogger(__name__)


def _build_html(jobs: list[dict]) -> str:
    now     = datetime.now().strftime("%d %b %Y, %I:%M %p")
    cards   = ""

    for j in jobs:
        pct     = j.get("match_pct", 0)
        # colour band
        if pct >= 75:
            badge_color = "#16a34a"   # green
        elif pct >= 55:
            badge_color = "#d97706"   # amber
        else:
            badge_color = "#dc2626"   # red

        matched = ", ".join(j.get("matched_skills", [])[:8]) or "–"
        missing = ", ".join(j.get("missing_skills", [])[:8]) or "–"

        cards += f"""
        <div style="background:#ffffff;border:1px solid #e5e7eb;border-radius:10px;
                    padding:20px;margin-bottom:20px;box-shadow:0 1px 4px rgba(0,0,0,.06);">
          <div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap;">
            <span style="background:{badge_color};color:#fff;font-weight:700;
                         font-size:22px;padding:4px 14px;border-radius:20px;">
              {pct}%
            </span>
            <div>
              <div style="font-size:18px;font-weight:700;color:#111827;">
                {j['title']}
              </div>
              <div style="color:#6b7280;font-size:14px;">
                {j['company']} &nbsp;|&nbsp; {j['location']} &nbsp;|&nbsp;
                <span style="color:#6366f1;font-weight:600;">{j['source']}</span>
              </div>
            </div>
          </div>

          <div style="margin-top:14px;font-size:13px;color:#374151;
                      background:#f9fafb;border-radius:6px;padding:10px;">
            {j.get('match_summary', '')}
          </div>

          <table style="margin-top:12px;width:100%;font-size:13px;border-collapse:collapse;">
            <tr>
              <td style="padding:6px 10px;background:#dcfce7;border-radius:6px 0 0 6px;
                          color:#166534;font-weight:600;width:50%;vertical-align:top;">
                ✅ Matched skills<br>
                <span style="font-weight:400;">{matched}</span>
              </td>
              <td style="width:8px;"></td>
              <td style="padding:6px 10px;background:#fee2e2;border-radius:0 6px 6px 0;
                          color:#991b1b;font-weight:600;width:50%;vertical-align:top;">
                ⚠️ Skill gaps<br>
                <span style="font-weight:400;">{missing}</span>
              </td>
            </tr>
          </table>

          <div style="margin-top:14px;">
            <a href="{j['apply_url']}"
               style="display:inline-block;background:#4f46e5;color:#fff;
                      padding:9px 22px;border-radius:6px;text-decoration:none;
                      font-weight:600;font-size:14px;">
              Apply Now →
            </a>
          </div>
        </div>
        """

    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
             background:#f3f4f6;margin:0;padding:24px;">
  <div style="max-width:680px;margin:auto;">

    <div style="background:linear-gradient(135deg,#4f46e5,#7c3aed);color:#fff;
                padding:28px 24px;border-radius:12px 12px 0 0;text-align:center;">
      <div style="font-size:28px;font-weight:800;">🎯 Job Match Report</div>
      <div style="font-size:14px;opacity:.85;margin-top:6px;">
        {len(jobs)} jobs matched ≥ {MIN_MATCH_PCT}% &nbsp;·&nbsp; {now}
      </div>
    </div>

    <div style="background:#f3f4f6;padding:20px;">
      {cards}
    </div>

    <div style="text-align:center;color:#9ca3af;font-size:12px;padding:12px;">
      Generated by Job Automation Script &nbsp;·&nbsp; Powered by Claude AI
    </div>

  </div>
</body>
</html>"""
    return html


def send_email(jobs: list[dict]) -> bool:
    """Send the match report. Returns True on success."""
    if not jobs:
        log.info("No jobs to email.")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = (
        f"🎯 {len(jobs)} Job Match(es) Found — "
        f"{datetime.now().strftime('%d %b %Y')}"
    )
    msg["From"]    = GMAIL_SENDER
    msg["To"]      = NOTIFY_EMAIL

    # Plain-text fallback
    plain_lines = [f"Job Match Report – {datetime.now().strftime('%d %b %Y')}\n"]
    for j in jobs:
        plain_lines.append(
            f"\n[{j['match_pct']}%] {j['title']} @ {j['company']} ({j['source']})\n"
            f"Apply: {j['apply_url']}\n"
            f"Matched: {', '.join(j.get('matched_skills', []))}\n"
            f"Missing: {', '.join(j.get('missing_skills', []))}\n"
        )
    msg.attach(MIMEText("\n".join(plain_lines), "plain"))
    msg.attach(MIMEText(_build_html(jobs),      "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(GMAIL_SENDER, GMAIL_PASSWORD)
            smtp.sendmail(GMAIL_SENDER, NOTIFY_EMAIL, msg.as_string())
        log.info("✅ Email sent to %s with %d matched jobs.", NOTIFY_EMAIL, len(jobs))
        return True
    except smtplib.SMTPAuthenticationError:
        log.error("Gmail auth failed. Make sure you're using an App Password "
                  "(https://myaccount.google.com/apppasswords).")
        return False
    except Exception as e:
        log.error("Failed to send email: %s", e)
        return False
